// <auto-generated />
using System;
using InsigniApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsigniApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250429164510_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsigniApi.Models.Entities.Scout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScoutGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tennure")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScoutGroupId");

                    b.ToTable("Scouts");
                });

            modelBuilder.Entity("InsigniApi.Models.Entities.ScoutGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScoutGroups");
                });

            modelBuilder.Entity("InsigniApi.Models.Entities.Scout", b =>
                {
                    b.HasOne("InsigniApi.Models.Entities.ScoutGroup", "ScoutGroup")
                        .WithMany("Scouts")
                        .HasForeignKey("ScoutGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoutGroup");
                });

            modelBuilder.Entity("InsigniApi.Models.Entities.ScoutGroup", b =>
                {
                    b.Navigation("Scouts");
                });
#pragma warning restore 612, 618
        }
    }
}
