// <auto-generated />
using System;
using InsigniApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsigniApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250430062316_ScoutInsigniaRelations")]
    partial class ScoutInsigniaRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssignmentScout", b =>
                {
                    b.Property<Guid>("CompletedAssignmentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScoutsWithAssignmentId")
                        .HasColumnType("uuid");

                    b.HasKey("CompletedAssignmentsId", "ScoutsWithAssignmentId");

                    b.HasIndex("ScoutsWithAssignmentId");

                    b.ToTable("ScoutAssignments", (string)null);
                });

            modelBuilder.Entity("InsigniApi.Models.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InsigniaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InsigniaId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("InsigniApi.Models.Entities.Insignia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredAssignments")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Insignias");
                });

            modelBuilder.Entity("InsigniApi.Models.Entities.Scout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScoutGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tennure")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScoutGroupId");

                    b.ToTable("Scouts");
                });

            modelBuilder.Entity("InsigniApi.Models.Entities.ScoutGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScoutGroups");
                });

            modelBuilder.Entity("InsigniaScout", b =>
                {
                    b.Property<Guid>("CompletedInsigniasId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScoutsWithInsigniaId")
                        .HasColumnType("uuid");

                    b.HasKey("CompletedInsigniasId", "ScoutsWithInsigniaId");

                    b.HasIndex("ScoutsWithInsigniaId");

                    b.ToTable("ScoutInsignias", (string)null);
                });

            modelBuilder.Entity("AssignmentScout", b =>
                {
                    b.HasOne("InsigniApi.Models.Entities.Assignment", null)
                        .WithMany()
                        .HasForeignKey("CompletedAssignmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsigniApi.Models.Entities.Scout", null)
                        .WithMany()
                        .HasForeignKey("ScoutsWithAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsigniApi.Models.Entities.Assignment", b =>
                {
                    b.HasOne("InsigniApi.Models.Entities.Insignia", "Insignia")
                        .WithMany("Assignments")
                        .HasForeignKey("InsigniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insignia");
                });

            modelBuilder.Entity("InsigniApi.Models.Entities.Scout", b =>
                {
                    b.HasOne("InsigniApi.Models.Entities.ScoutGroup", "ScoutGroup")
                        .WithMany("Scouts")
                        .HasForeignKey("ScoutGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoutGroup");
                });

            modelBuilder.Entity("InsigniaScout", b =>
                {
                    b.HasOne("InsigniApi.Models.Entities.Insignia", null)
                        .WithMany()
                        .HasForeignKey("CompletedInsigniasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsigniApi.Models.Entities.Scout", null)
                        .WithMany()
                        .HasForeignKey("ScoutsWithInsigniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsigniApi.Models.Entities.Insignia", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("InsigniApi.Models.Entities.ScoutGroup", b =>
                {
                    b.Navigation("Scouts");
                });
#pragma warning restore 612, 618
        }
    }
}
